/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as InstallRouteImport } from './routes/install'
import { Route as DesignPrinciplesRouteImport } from './routes/design-principles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as ComponentsNameRouteImport } from './routes/components/$name'

const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignPrinciplesRoute = DesignPrinciplesRouteImport.update({
  id: '/design-principles',
  path: '/design-principles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsNameRoute = ComponentsNameRouteImport.update({
  id: '/components/$name',
  path: '/components/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-principles': typeof DesignPrinciplesRoute
  '/install': typeof InstallRoute
  '/philosophy': typeof PhilosophyRoute
  '/roadmap': typeof RoadmapRoute
  '/components/$name': typeof ComponentsNameRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-principles': typeof DesignPrinciplesRoute
  '/install': typeof InstallRoute
  '/philosophy': typeof PhilosophyRoute
  '/roadmap': typeof RoadmapRoute
  '/components/$name': typeof ComponentsNameRoute
  '/components': typeof ComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design-principles': typeof DesignPrinciplesRoute
  '/install': typeof InstallRoute
  '/philosophy': typeof PhilosophyRoute
  '/roadmap': typeof RoadmapRoute
  '/components/$name': typeof ComponentsNameRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-principles'
    | '/install'
    | '/philosophy'
    | '/roadmap'
    | '/components/$name'
    | '/components/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-principles'
    | '/install'
    | '/philosophy'
    | '/roadmap'
    | '/components/$name'
    | '/components'
  id:
    | '__root__'
    | '/'
    | '/design-principles'
    | '/install'
    | '/philosophy'
    | '/roadmap'
    | '/components/$name'
    | '/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignPrinciplesRoute: typeof DesignPrinciplesRoute
  InstallRoute: typeof InstallRoute
  PhilosophyRoute: typeof PhilosophyRoute
  RoadmapRoute: typeof RoadmapRoute
  ComponentsNameRoute: typeof ComponentsNameRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-principles': {
      id: '/design-principles'
      path: '/design-principles'
      fullPath: '/design-principles'
      preLoaderRoute: typeof DesignPrinciplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$name': {
      id: '/components/$name'
      path: '/components/$name'
      fullPath: '/components/$name'
      preLoaderRoute: typeof ComponentsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignPrinciplesRoute: DesignPrinciplesRoute,
  InstallRoute: InstallRoute,
  PhilosophyRoute: PhilosophyRoute,
  RoadmapRoute: RoadmapRoute,
  ComponentsNameRoute: ComponentsNameRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
