name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - name: Build libraries
        run: npx nx run-many -t build --projects=spec,angular,react,vue,create-workspace,create-atelier-ui-workspace --skip-nx-cache

      - name: Publish @atelier-ui/spec
        run: npm publish dist/libs/spec --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @atelier-ui/angular
        run: npm publish dist/libs/angular --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @atelier-ui/react
        run: npm publish dist/libs/react --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @atelier-ui/vue
        run: npm publish dist/libs/vue --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @atelier-ui/create-workspace
        run: npm publish dist/libs/create-workspace --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish create-atelier-ui-workspace
        run: npm publish dist/libs/create-atelier-ui-workspace --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
